package app.coinverse.contentviewmodel.testCases

import app.coinverse.contentviewmodel.PlayContentTest
import app.coinverse.contentviewmodel.mockArticleContent
import app.coinverse.contentviewmodel.mockDbContentListForDay
import app.coinverse.contentviewmodel.mockYouTubeContent
import app.coinverse.utils.*
import java.util.stream.Stream

fun playContentTestCases() = Stream.of(
        // ARTICLE
        // MAIN
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.MAIN,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.LOADING,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TXT_FILE_PATH,
                mockGetAudiocastError = "",
                mockPreviewImageUrl = "",
                mockPreviewImageByteArray = ByteArray(0)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.MAIN,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.CONTENT,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TXT_FILE_PATH,
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(1)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.MAIN,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.ERROR,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TTS_CHAR_LIMIT_ERROR,
                mockGetAudiocastError = MOCK_TTS_CHAR_LIMIT_ERROR_MESSAGE,
                mockPreviewImageUrl = "",
                mockPreviewImageByteArray = ByteArray(0)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.MAIN,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.ERROR,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = "",
                mockGetAudiocastError = MOCK_CONTENT_PLAY_ERROR,
                mockPreviewImageUrl = "",
                mockPreviewImageByteArray = ByteArray(0)),
        // SAVED
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.SAVED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.LOADING,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TXT_FILE_PATH,
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(1)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.SAVED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.CONTENT,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0, mockFilePath = MOCK_TXT_FILE_PATH,
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(1)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.SAVED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.ERROR,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TTS_CHAR_LIMIT_ERROR,
                mockGetAudiocastError = MOCK_TTS_CHAR_LIMIT_ERROR_MESSAGE,
                mockPreviewImageUrl = "",
                mockPreviewImageByteArray = ByteArray(0)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.SAVED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.ERROR,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = "",
                mockGetAudiocastError = MOCK_CONTENT_PLAY_ERROR,
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(0)),
        // DISMISSED
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.DISMISSED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.LOADING,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TXT_FILE_PATH,
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(1)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.DISMISSED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.CONTENT,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TXT_FILE_PATH,
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(1)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.DISMISSED, timeframe = Timeframe.DAY,
                lceState = LCE_STATE.ERROR,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0,
                mockFilePath = MOCK_TTS_CHAR_LIMIT_ERROR,
                mockGetAudiocastError = MOCK_TTS_CHAR_LIMIT_ERROR_MESSAGE,
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(0)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.DISMISSED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.ERROR,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockArticleContent,
                mockPosition = 0, mockFilePath = "",
                mockGetAudiocastError = MOCK_CONTENT_PLAY_ERROR,
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(0)),

        // YOUTUBE
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.MAIN,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.CONTENT,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockYouTubeContent,
                mockPosition = 0,
                mockFilePath = "",
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(0)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.SAVED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.CONTENT,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockYouTubeContent,
                mockPosition = 0,
                mockFilePath = "",
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(0)),
        PlayContentTest(
                isRealtime = false,
                feedType = FeedType.DISMISSED,
                timeframe = Timeframe.DAY,
                lceState = LCE_STATE.CONTENT,
                mockFeedList = mockDbContentListForDay,
                mockContent = mockYouTubeContent,
                mockPosition = 0,
                mockFilePath = "",
                mockGetAudiocastError = "",
                mockPreviewImageUrl = MOCK_PREVIEW_IMAGE,
                mockPreviewImageByteArray = ByteArray(0)))